processed 4 tasks

task 1 'publish'. lines 6-13:
created: object(103)
written: object(102)

task 2 'run'. lines 14-16:
Error: Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidFunctionSignature, source: None } }

task 3 'run'. lines 17-17:
Error: Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VmError, source: None } }
